### ISSUE TITLE
IPTV Recorder with live tv protected by DRM - Handle errors

### ISSUE THREAD

**Issue by wwark** [primaeval/plugin.video.iptv.recorder#28]
Hi @primaeval,

Thank you for this plugin very usefull.
I co-develop this add-on (https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore) with @SylvainCecchetto.
We proposed some lives TV DRM protected in it like Quest TV or Quest Red for example.

We also make this documentation to use IPTV Recoder (with PVR IPTV Simple) (https://catch-up-tv-and-more.github.io/live_tv_installation/#iv-recording-lives-tv)

If you try to record Quest TV for example no issue is raised by IPTV Recorder to inform this content cannot be recorded and the job is still running.
The ITPV Recorder create a file with the size of 0 ko and if you try to read it in Kodi. You need to kill the instance of Kodi.

Do you think it is possible to raise error message (notification) if this case, stop the job and remove the file of 0k?

Thanks for your help and your time in this add-on,
Wwark

**Comment by primaeval** [comment]
You'll have to find out why it was still running first. 

Use the Settings \ Debug \ debug ffmpeg stdout/stderr. 
Then try to record something that fails and look in the addon_data\plugin.video.iptv.recorder.jobs file for the stderr file.
It should tell you what is wrong.

Also try turning off the ffmpeg reconnect options in Settings.

**Comment by wwark** [comment]
I think it is not possible to record these type stream because they are DRM protected.

I have done the test requested with debug activated.
**File created 0 ko**
wark@wark-home:~/Dev/work$ ls -l "/home/wark/.kodi/temp/Other/M6 boutique/M6 boutique - M6 - 2019-04-30 08-50.ts"
-rw-rw-r-- 1 wark wark 0 avril 30 09:00 '/home/wark/.kodi/temp/Other/M6 boutique/M6 boutique - M6 - 2019-04-30 08-50.ts'
**Attached files created in jobs directory.**
[a426e7fa-6b15-11e9-9282-e86a64592c99.zip](https://github.com/primaeval/plugin.video.iptv.recorder/files/3130190/a426e7fa-6b15-11e9-9282-e86a64592c99.zip)
No clues on them.
The job is still running.

I have done also the test with turning off ffmpeg reconnect. I have the same behavior.

**Comment by primaeval** [comment]
Correct. Anything that goes through inputstream.adaptive cannot be recorded by IPTV Recorder. inputstream.adaptive does not expose the actual url for the stream. If you have the option choose hls streams. There is no error because Kodi plays it quite happily but doesn't tell you the base url.

**Comment by wwark** [comment]
Ok thank you for these informations.
The main point of my request is to be able to notify the user this live tv is not recordable and maybe stop (not start it?) the job in IPTV recorder side and remove the file of 0k created.

We proposed m3u file that can be configured in PVR Simple IPTV.
In this m3u file we call our add-on like that `plugin://plugin.video.catchuptvandmore/main/live_bridge/?item_id=m6&item_module=resources.lib.channels.fr.6play&item_dict={}`. The python file of this channel is executed to play (throught PVR SImple IPTV) or to record (through IPTV Recorder)

I don't see how on our side we can stop the job of ITPV Recorder (means from our add-on)  or notify the end user.

Do you think on IPTV Recorder side it is possible not start the job of recording if the input is  `None` (not hls) like in this case and notif this content is not recordable ? 

THanks for your help

**Comment by primaeval** [comment]
Try this.
https://github.com/primaeval/plugin.video.iptv.recorder/commit/fd97cec21534c479149bd5892a1c148c25397ead
If it works I'll release it.

**Comment by wwark** [comment]
Not working.
[kodi.log](https://github.com/primaeval/plugin.video.iptv.recorder/files/3130576/kodi.log)
The IPTV Recorder job is created and the notification "can not record" is not shown.

**Comment by primaeval** [comment]
There won't be anything in the log as the notification is an xbmc.dialog.notification.

Turn kodi debug logging on and try this.
https://github.com/primaeval/plugin.video.iptv.recorder/commit/d2728b8910a8ef1a5fdc3c2e6755e43fa06c8527

If it works it should say
''
quit
in the log where '' is nothing because it can't find new_url.

**Comment by wwark** [comment]
[kodi.log](https://github.com/primaeval/plugin.video.iptv.recorder/files/3130702/kodi.log)
The inpustream.apdative log part we have this url `https://m6.live.6cloud.fr/out/u/m6_sd_p_video_1_3_init.mp4?m=155438373` 

thank you

**Comment by primaeval** [comment]
It will not work with inputstream.adaptive.

This will make the prints a bit easier to see with XXX
https://github.com/primaeval/plugin.video.iptv.recorder/commit/c15dabd96a94169359b3ff17b8a7bd496222a2e6

**Comment by wwark** [comment]
Sorry for the delay.
the new log below
[kodi.log](https://github.com/primaeval/plugin.video.iptv.recorder/files/3134009/kodi.log)

**Comment by primaeval** [comment]
Use main.py from the x branch.

https://github.com/primaeval/plugin.video.iptv.recorder/commit/2a9f6f8de32a87d61d2dfe7b691ab19662b05eda

**Comment by wwark** [comment]
[kodi.log](https://github.com/primaeval/plugin.video.iptv.recorder/files/3134044/kodi.log)

2019-05-01 10:22:15.224 T:140653088339712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: invalid syntax (3a091354-6bea-11e9-9282-e86a64592c99.py, line 6)
                                              File "/home/wark/.kodi/userdata/addon_data/plugin.video.iptv.recorder/jobs/3a091354-6bea-11e9-9282-e86a64592c99.py", line 6
                                                print repr('XXX url',plugin://plugin.video.catchuptvandmore/main/live_bridge/?item_id=m6&item_module=resources.lib.channels.fr.6play&item_dict={})
                                                                           ^
                                            SyntaxError: invalid syntax
                                            -->End of Python script error report<--

**Comment by primaeval** [comment]
https://github.com/primaeval/plugin.video.iptv.recorder/commit/6c29fe38ba674e7e2b1509f9a1fecc6b6e079972

**Comment by wwark** [comment]
I have this issue below so I change a bit the main.py in attchement
[main.zip](https://github.com/primaeval/plugin.video.iptv.recorder/files/3134072/main.zip)
New log with my main.py
[kodi.log](https://github.com/primaeval/plugin.video.iptv.recorder/files/3134075/kodi.log)


2019-05-01 10:32:20.264 T:140323186267904   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: repr() takes exactly one argument (2 given)
                                            Traceback (most recent call last):
                                              File "/home/wark/.kodi/userdata/addon_data/plugin.video.iptv.recorder/jobs/a28e9024-6beb-11e9-9282-e86a64592c99.py", line 6, in <module>
                                                print repr('XXX url','plugin://plugin.video.catchuptvandmore/main/live_bridge/?item_id=m6&item_module=resources.lib.channels.fr.6play&item_dict={}')
                                            TypeError: repr() takes exactly one argument (2 given)
                                            -->End of Python script error report<--

**Comment by primaeval** [comment]
new_url is the only thing I need to see.
